### ISSUE TITLE
t

### ISSUE THREAD

**Issue by prakriti1234567** [N8theGrape/CSP#1]
#Project 1 Video Game

import turtle

# Screen
wn = turtle.Screen()

# Provide the correct file path to the downloaded image
imagePath = "https://mathmonks.com/wp-content/uploads/2020/06/Hexagon.jpg"

# Set the background image
wn.bgpic(imagePath)

#Turtle Player
Pen = turtle.Turtle()
Pen.shape("classic")
Pen.color("black")
Pen.pendown()

def k1():
    Pen.forward(45)

def k2():
    Pen.left(45)

def k3():
    Pen.right(45)

def k4():
    Pen.back(45)

wn.onkey(k1, "Up")
wn.onkey(k2, "Left")
wn.onkey(k3, "Right")
wn.onkey(k4, "Down")

wn.mainloop()

**Comment by prakriti1234567** [comment]
#Project 1 Video Game

import turtle

# Screen
wn = turtle.Screen()

# Provide the correct file path to the downloaded image
imagePath = "https://mathmonks.com/wp-content/uploads/2020/06/Hexagon.jpg"

# Set the background image
wn.bgpic(imagePath)


#Turtle Player
Pen = turtle.Turtle()
Pen.shape("classic")
Pen.color("black")
Pen.pendown()


def k1():
    Pen.forward(45)


def k2():
    Pen.left(45)


def k3():
    Pen.right(45)


def k4():
    Pen.back(45)


wn.onkey(k1, "Up")
wn.onkey(k2, "Left")
wn.onkey(k3, "Right")
wn.onkey(k4, "Down")


wn.mainloop()

**Comment by prakriti1234567** [comment]
#Project 1 Video Game

import turtle

# Screen
wn = turtle.Screen()

# Provide the correct file path to the downloaded image
imagePath = "https://mathmonks.com/wp-content/uploads/2020/06/Hexagon.jpg"

# Set the background image
wn.bgpic(imagePath)


#Turtle Player
Pen = turtle.Turtle()
Pen.shape("classic")
Pen.color("black")
Pen.pendown()


def k1():
    Pen.forward(45)


def k2():
    Pen.left(45)


def k3():
    Pen.right(45)


def k4():
    Pen.back(45)


wn.onkey(k1, "Up")
wn.onkey(k2, "Left")
wn.onkey(k3, "Right")
wn.onkey(k4, "Down")


wn.mainloop()

**Comment by CrookedTwig4** [comment]
#Project 1 Video Game

import turtle

# Screen
wn = turtle.Screen()

# Set the background image
wn.bgpic("image.png")


#Turtle Player
Pen = turtle.Turtle()
Pen.shape("classic")
Pen.color("black")
Pen.pendown()


def k1():
    Pen.forward(45)


def k2():
    Pen.left(45)


def k3():
    Pen.right(45)


def k4():
    Pen.back(45)


wn.onkey(k1, "Up")
wn.onkey(k2, "Left")
wn.onkey(k3, "Right")
wn.onkey(k4, "Down")


wn.mainloop()
